cluster:
  kubernetesVersion: "v1.25.10"

prismCentral:
  inject: true
  address: crimson-pc.dachlab.net
  insecure: false
  port: 9440
  username: admin

controlplane:
  replicas: 1

nodes:
  replicas: 1

kubeVip:
  cloudProvider:
    enabled: false

kcpMachine:
  os: ubuntu-2204

mdMachine:
  os: ubuntu-2204

machinehealthcheck: false

ccm:
  enabled: true
  replicas: 1
  enableCustomLabeling: false

metricsServer:
  enabled: false

csi:
  snapshot: false
  enable_csi2: false
  enable_csi3: false
  createSecret: false
  storageContainer: k8s