cluster:
  kubernetesVersion: "v1.25.10"

controlPlaneEndpoint:
  host: 10.48.38.85

prismCentral:
  inject: true
  address: crimson-pc.dachlab.net
  insecure: false
  port: 9440
  username: admin

controlplane:
  replicas: 1

nodes:
  replicas: 1

kubeVip:
  cloudProvider:
    enabled: false

kcpMachine:
  cluster: crimson
  os: ubuntu-2204
  subnet: phx-routed-55-IPAM

mdMachine:
  cluster: crimson
  os: ubuntu-2204
  subnet: phx-routed-55-IPAM

machinehealthcheck: false

ccm:
  enabled: false

metricsServer:
  enabled: true

csi:
  snapshot: false
  enable_csi2: false
  enable_csi3: false
  createSecret: false
  storageContainer: default