---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.cluster.name }}-credential
  namespace: {{ .Values.cluster.name }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.cluster.name }}-credential
    template:
      type: Opaque
      metadata: {}
      data:
        credentials: |
          [
            {
              "type": "basic_auth", 
              "data": { 
                "prismCentral":{
                  "username": "{{"{{"}} .user {{"}}"}}",
                  "password": "{{"{{"}} .pass {{"}}"}}"
                },
                "prismElements": null
              }
            }
          ]
  dataFrom:
  - extract:
      key: {{ .Values.credentialsecret.key }}