apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    cd-component: flow
    environment: '{{.name}}'
  name: '{{.name}}-per-cluster-settings'
  namespace: argocd
spec:
  destination:
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      project: default
      destination:
        name: ''
        namespace: '{{.name}}'
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: 'https://github.com/wolfganghuse/edge-k8s-argocd'
        path: 'common-helm-charts/crossplane-infrastructure/flow'
        targetRevision: 'test1'
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: HELM_VALUES
              value: |
                cluster:
                  name: "{{.name}}"
                  prismcentral: "{{.prismcentral}}"
                  user: <path:secret/data/prismcentral/{{.prismcentral}}#user>
                  pass: <path:secret/data/prismcentral/{{.prismcentral}}#pass>
                  endpoint: <path:secret/data/prismcentral/{{.prismcentral}}#endpoint>