apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-integration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/wolfganghuse/edge-k8s-argocd.git
          revision: test1
          files:
          - path: mgmt/prismcentral.yaml
      - list:
          elements: []
          elementsYaml: "{{ .key.prismcentral | toJson }}"
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      name: '{{.name}}-infrastructure-integration'
      labels: 
        cd-component: infrastructure
        environment: '{{.name}}'
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      project: default
      destination:
        name: ''
        namespace: '{{.name}}'
        server: 'https://kubernetes.default.svc'
      source:
        path: 'common-helm-charts/crossplane-infrastructure/images'
        repoURL: 'https://github.com/wolfganghuse/edge-k8s-argocd'
        targetRevision: 'test1'
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: HELM_VALUES
              value: |
                cluster:
                  name: "{{.name}}"
                  user: <path:secret/data/prismcentral/{{.name}}#user>
                  pass: <path:secret/data/prismcentral/{{.name}}#pass>
                  endpoint: <path:secret/data/prismcentral/{{.name}}#endpoint>