apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: workspace-{{ .Values.cluster.prismcentral }}-images
  annotations:
    meta.upbound.io/example-id: tf/v1beta1/workspace
    argocd.argoproj.io/sync-wave: "-8"
spec:
  forProvider:
    source: Inline
    module: |

      {{- range $i, $v := .Values.images }}
      resource "nutanix_image" "source-image-{{ $i }}" {

        provider = nutanix

        source_uri = "{{ $v.url }}"
        name = "{{ $v.name }}"
      }
      {{- end }}
      
  providerConfigRef:
    name: {{ .Values.cluster.prismcentral }}-providerconfig
  writeConnectionSecretToRef:
    namespace:  {{ .Values.cluster.prismcentral }}
    name: connection-{{ .Values.cluster.prismcentral }}-images