apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: workspace-{{ .Values.cluster.name }}-images
  annotations:
    meta.upbound.io/example-id: tf/v1beta1/workspace
spec:
  forProvider:
    source: Inline
    module: |
      resource "nutanix_image" "source_image_1_28" {

        provider = nutanix

        source_uri = "https://capx-img.s3.eu-west-3.amazonaws.com/ubuntu-2204-kube-v1.28.0.qcow2"
        name = "ubuntu-2204-kube-v1.28.0"
      }
      resource "nutanix_image" "source_image" {

        provider = nutanix

        source_uri = "https://capx-img.s3.eu-west-3.amazonaws.com/ubuntu-2204-kube-v1.27.4.qcow2"
        name = "ubuntu-2204-kube-v1.27.4"
      }
      resource "nutanix_image" "source_image_1_26" {

        provider = nutanix

        source_uri = "https://capx-img.s3.eu-west-3.amazonaws.com/ubuntu-2204-kube-v1.26.7.qcow2"
        name = "ubuntu-2204-kube-v1.26.7"
      }
      resource "nutanix_image" "source_image_1_25" {

        provider = nutanix

        source_uri = "https://capx-img.s3.eu-west-3.amazonaws.com/ubuntu-2204-kube-v1.25.12.qcow2"
        name = "ubuntu-2204-kube-v1.25.12"
      }
      
  providerConfigRef:
    name: {{ .Values.cluster.name }}-providerconfig
  writeConnectionSecretToRef:
    namespace:  {{ .Values.cluster.name }}
    name: connection-{{ .Values.cluster.name }}-images