apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ .Values.cluster.name }}-images
  annotations:
    meta.upbound.io/example-id: tf/v1beta1/workspace
spec:
  forProvider:
    source: Inline
    module: |
      resource "nutanix_image" "source_image" {

        provider = nutanix

        source_uri = "https://capx-img.s3.eu-west-3.amazonaws.com/ubuntu-2204-kube-v1.27.4.qcow2"
        name = "ubuntu-2204-kube-v1.27.4"
      }
  providerConfigRef:
    name: {{ .Values.cluster.name }}-providerconfig
  writeConnectionSecretToRef:
    namespace:  {{ .Values.cluster.name }}
    name: providerconfig-nutanix-images