apiVersion: operator.cluster.x-k8s.io/v1alpha1
kind: InfrastructureProvider
metadata:
 name: nutanix
 namespace: capx-system
spec:
 version: v1.2.3
 secretName: nutanix-variables
 secretNamespace: capx-system