configs:
  cm:
    accounts.secretoperator: apiKey
  params:
    server.insecure: true
  rbac:
    policy.csv: |
      p, role:apioperator, clusters, list, *, allow
      p, role:apioperator, clusters, get, *, allow
      p, role:apioperator, clusters, update, *, allow      
      p, role:apioperator, clusters, watch, *, allow
      p, role:apioperator, clusters, create, *, allow
      p, role:apioperator, clusters, delete, *, allow
      p, role:apioperator, clusters, patch, *, allow
      g, secretoperator, role:apioperator
server:
  ingress:
    enabled: true
    annotations: {
      cert-manager.io/cluster-issuer: letsencrypt-prod
    }
    ingressClassName: nginx
    hosts:
      - argocd.edge-management.dachlab.net
    tls:
    - hosts:
        - argocd.edge-management.dachlab.net
      secretName: argocd-tld-secret

repoServer:
  rbac:
    - verbs:
        - get
        - list
        - watch
      apiGroups:
        - ''
      resources:
        - secrets
        - configmaps
  initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8
      env:
        - name: AVP_VERSION
          value: 1.14.0
      command: [sh, -c]
      args:
        - >-
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools

  extraContainers:
    - name: avp-helm
      command: [/var/run/argocd/argocd-cmp-server]
      image: quay.io/argoproj/argocd:v2.7.9
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp-dir
        - mountPath: /home/argocd/cmp-server/config
          name: cmp-plugin
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin

  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: custom-tools
      emptyDir: {}
    - name: tmp-dir
      emptyDir: {}

# If you face issue with ArgoCD CRDs installation, then uncomment below section to disable it
#crds:
#  install: false