kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_AUTH_TYPE: "token"
  AVP_TYPE: "vault"
  VAULT_ADDR: "https://vault.edge-management.dachlab.net"
  VAULT_TOKEN: Your Vault token
  