ingress:
  enabled: true
  annotations: {
    cert-manager.io/cluster-issuer: letsencrypt-prod
  }
  ingressClassName: nginx
  hosts: ["grafana.edge-management.dachlab.net"]
  tls:
  - hosts:
      - grafana.edge-management.dachlab.net
    secretName: vault-tld-secret
persistence:
  enabled: true
  storageClassName: default-storageclass
