apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: argo-cluster-generation-from-capi
  annotations:
    policies.kyverno.io/title: Argo Cluster Secret Generation From CAPI Secret
    policies.kyverno.io/category: Argo
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      This policy generates and synchronizes Argo CD cluster secrets from cluster CAPI secrets.
spec:
  generateExistingOnPolicyUpdate: true
  rules:
    - name: capi-secret
      match:
        all:
        - resources:
            kinds:
            - Secret
            names:
            - "*-kubeconfig"
            selector:
              matchExpressions:
              - key: "cluster.x-k8s.io/cluster-name"
                operator: Exists
      context:
      - name: clusterName
        variable:
          value: "{{ replace_all('{{request.object.metadata.name}}', '-kubeconfig', '') }}"
          jmesPath: 'to_string(@)'
      - name: clusterPrefixedName
        variable:
          value: "{{ join('-', ['cluster', clusterName]) }}"
          jmesPath: 'to_string(@)'
      - name: extraLabels
        variable:
          value:
            argocd.argoproj.io/secret-type: cluster
            clusterId: "{{ clusterName }}"
      - name: serverName
        variable:
          value: "{{ request.object.data.value | base64_decode(@) | parse_yaml(@).clusters[0].cluster.server }}"
          jmesPath: 'to_string(@)'
      - name: certData
        variable:
          value: "{{ request.object.data.value | base64_decode(@) | parse_yaml(@).users[0].user.\"client-certificate-data\" }}"
          jmesPath: 'to_string(@)'
      - name: keyData
        variable:
          value: "{{ request.object.data.value | base64_decode(@) | parse_yaml(@).users[0].user.\"client-key-data\" }}"
          jmesPath: 'to_string(@)'
      - name: caData
        variable:
          value: "{{ request.object.data.value | base64_decode(@) | parse_yaml(@).clusters[0].cluster.\"certificate-authority-data\" }}"
          jmesPath: 'to_string(@)'
      - name: dataConfig
        variable:
          value: |
            {
              "tlsClientConfig": {
                "insecure": false,
                "certData": "{{ certData }}",
                "keyData": "{{ keyData }}",
                "caData": "{{ caData }}"
              }
            }
          jmesPath: 'to_string(@)'
      generate:
        synchronize: true
        apiVersion: v1
        kind: Secret
        name: "{{ clusterPrefixedName }}"
        namespace: argocd
        data:
          metadata:
            labels:
              "{{ extraLabels }}"
          type: Opaque
          data:
            name: "{{ clusterPrefixedName | base64_encode(@) }}"
            server: "{{ serverName | base64_encode(@) }}"
            config: "{{ dataConfig | base64_encode(@) }}"