apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nkex1
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    name: ''
    namespace: nkex1
    server: 'https://kubernetes.default.svc'
  sources:
  - repoURL: 'git@github.com:nutanix-cloud-native/nkex-cluster.git'
    path: .
    targetRevision: wolf
    helm:
      valueFiles:
      - $values/mgmt/edge-base-values.yaml
      parameters:
      - name: "controlPlaneEndpoint.host"
        value: 10.48.38.89
  - repoURL: 'https://github.com/wolfganghuse/edge-k8s-argocd.git'
    targetRevision: HEAD
    ref: values