apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: edge-k8s
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/wolfganghuse/edge-k8s-argocd.git
          revision: env-littlelab1
          files:
          - path: mgmt/edge-k8s-clusters.yaml
      - list:
          elements: []
          elementsYaml: "{{ .key.clusters | toJson }}"
  template:
    metadata:
      name: '{{.name}}'
    spec:
      syncPolicy:
        automated:
          prune: false
        syncOptions:
          - CreateNamespace=true
      project: default
      destination:
        name: ''
        namespace: '{{.name}}'
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: 'git@github.com:nutanix-cloud-native/nkex-cluster.git'
        path: .
        targetRevision: main
        helm:
          parameters:
          - name: "controlPlaneEndpoint.host"
            value: '{{.controlplane_ip}}'
          - name: "mdMachine.cluster"
            value: '{{.cluster}}'
          - name: "kcpMachine.cluster"
            value: '{{.cluster}}'
          - name: "mdMachine.subnet"
            value: '{{.subnet}}'
          - name: "kcpMachine.subnet"
            value: '{{.subnet}}'
          - name: "prismCentral.password"
            value: '$NUTANIX_PASSWORD'      
          - name: "prismCentral.address"
            value: '{{.prismcentral}}'      
          - name: "prismCentral.inject"
            value: true
          - name: "kcpMachine.os"
            value: "ubuntu-2204"
          - name: "mdMachine.os"
            value: "ubuntu-2204"