apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flow-rules
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/wolfganghuse/edge-k8s-argocd.git
          revision: test1
          files:
          - path: mgmt/edge-k8s-clusters.yaml
      - list:
          elements: []
          elementsYaml: "{{ .key.clusters | toJson }}"
  template:
    metadata:
      name: '{{.name}}-flow'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      labels: 
        cd-component: flow
        environment: '{{.name}}'
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      project: default
      destination:
        name: ''
        namespace: '{{.name}}'
        server: 'https://kubernetes.default.svc'
      sources:
      - repoURL: 'https://github.com/wolfganghuse/edge-k8s-argocd'
        path: 'common-helm-charts/crossplane-infrastructure/categories'
        targetRevision: 'test1'
        helm:
          parameters:
          - name: "cluster.name"
            value: '{{.name}}'
          - name: "cluster.prismcentral"
            value: '{{.prismcentral}}'
      - repoURL: 'https://github.com/wolfganghuse/edge-k8s-argocd'
        path: 'common-helm-charts/crossplane-infrastructure/flow'
        targetRevision: 'test1'
        helm:
          parameters:
          - name: "cluster.name"
            value: '{{.name}}'
          - name: "cluster.prismcentral"
            value: '{{.prismcentral}}'