apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-integration
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/wolfganghuse/edge-k8s-argocd.git
          revision: main
          files:
          - path: mgmt/prismcentral.yaml
      - list:
          elements: []
          elementsYaml: "{{ .key.prismcentral | toJson }}"
  template:
    metadata:
      name: '{{.name}}-infrastructure-integration'
      labels: 
        cd-component: infrastructure
        environment: '{{.name}}'
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      project: default
      destination:
        name: ''
        namespace: '{{.name}}'
        server: 'https://kubernetes.default.svc'
      sources:
      - repoURL: 'https://github.com/wolfganghuse/edge-k8s-argocd'
        path: 'common-helm-charts/crossplane-infrastructure/provider'
        targetRevision: 'main'
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: HELM_VALUES
              value: |
                cluster:
                  name: "{{.name}}"
                  prismcentral: "{{.name}}"
                  user: <path:secret/data/prismcentral/{{.name}}#user>
                  pass: <path:secret/data/prismcentral/{{.name}}#pass>
                  endpoint: <path:secret/data/prismcentral/{{.name}}#endpoint>
      - repoURL: 'https://github.com/wolfganghuse/edge-k8s-argocd'
        path: 'common-helm-charts/crossplane-infrastructure/images'
        targetRevision: 'main'
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: HELM_VALUES
              value: |
                cluster:
                  prismcentral: "{{.name}}"
                  user: <path:secret/data/prismcentral/{{.name}}#user>
                  pass: <path:secret/data/prismcentral/{{.name}}#pass>
                  endpoint: <path:secret/data/prismcentral/{{.name}}#endpoint>
                images:
                - name: ubuntu-2204-kube-v1.28.0
                  url: https://capx-img.s3.eu-west-3.amazonaws.com/ubuntu-2204-kube-v1.28.0.qcow2
                - name: ubuntu-2204-kube-v1.27.4
                  url: https://capx-img.s3.eu-west-3.amazonaws.com/ubuntu-2204-kube-v1.27.4.qcow2
                - name: ubuntu-2204-kube-v1.26.7
                  url: https://capx-img.s3.eu-west-3.amazonaws.com/ubuntu-2204-kube-v1.26.7.qcow2
                - name: ubuntu-2204-kube-v1.25.12
                  url: https://capx-img.s3.eu-west-3.amazonaws.com/ubuntu-2204-kube-v1.25.12.qcow2
