apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}-workload'
      labels: 
        cd-component: workload
        environment: '{{name}}'
    spec:
      syncPolicy:
        automated:
          prune: true
      project: default
      source:
        repoURL: 'https://github.com/wolfganghuse/edge-k8s-argocd.git'
        path: workload
        targetRevision: test1
      destination:
        server: '{{server}}'