apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ .Values.cluster.name }}-isolation-rule
  namespace: {{ .Values.cluster.name }}
  # annotations:
  #   meta.upbound.io/example-id: tf/v1beta1/workspace
spec:
  forProvider:
    source: Inline
    module: |
      resource "nutanix_network_security_rule" "isolation" {
          name        = "{{ .Values.cluster.name }}-isolation-rule"
          description = "{{ .Values.cluster.name }}-isolation-rule"

          isolation_rule_action = "APPLY"

          isolation_rule_first_entity_filter_kind_list = ["vm"]
          isolation_rule_first_entity_filter_type      = "CATEGORIES_MATCH_ALL"
          isolation_rule_first_entity_filter_params {
              name   = "Environment"
              values = ["Dev"]
          }

          isolation_rule_second_entity_filter_kind_list = ["vm"]
          isolation_rule_second_entity_filter_type      = "CATEGORIES_MATCH_ALL"
          isolation_rule_second_entity_filter_params {
              name   = "Environment"
              values = ["Production"]
          }
      }

  writeConnectionSecretToRef:
    namespace:  {{ .Values.cluster.name }}
    name: providerconfig-nutanix