apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capx-env
  namespace: argocd
spec:
  source:
    path: apps/app-of-apps/apps
    repoURL: 'https://github.com/wolfganghuse/edge-k8s-argocd'
    targetRevision: test1
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true